<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_CCEM_app_CCEM_top_bar_f84b5e74-232f-_7cf281</name>
   <tag></tag>
   <elementGuidId>b214b9b7-3a35-4b4a-aa56-fe9a239c404b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;app_CCEM_top_bar_f84b5e74-232f-4833-ac7f-feb1b12066db&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='app_CCEM_top_bar_f84b5e74-232f-4833-ac7f-feb1b12066db']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://347982.apps.zdusercontent.com/347982/assets/1633050534-1ca5649b20542a8c9ed713e1b6969dcc/resources/html/ces_top.html?origin=https%3A%2F%2Fdaekyo-ccm.zendesk.com&amp;app_guid=f84b5e74-232f-4833-ac7f-feb1b12066db</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>app_CCEM_top_bar_f84b5e74-232f-4833-ac7f-feb1b12066db</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-popups-to-escape-sandbox allow-scripts allow-same-origin allow-downloads</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>geolocation;autoplay;microphone;camera;midi;encrypted-media;clipboard-write;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember2519&quot;)/div[@class=&quot;app_view_outer popover-inner&quot;]/div[@class=&quot;iframe_app_view_wrapper&quot;]/div[@class=&quot;app_view_wrapper&quot;]/div[@class=&quot;app_view app-347982 apps_top_bar&quot;]/iframe[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='app_CCEM_top_bar_f84b5e74-232f-4833-ac7f-feb1b12066db']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember2519']/div[2]/div/div/div/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/iframe</value>
   </webElementXpaths>
</WebElementEntity>
