<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__logo</name>
   <tag></tag>
   <elementGuidId>ffbe307b-11e7-41b8-8286-67ed0228a539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ember2263 > div.app_view_outer.popover-inner > div.iframe_app_view_wrapper > header > img.logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ember2263']/div[2]/div/header/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://347982.apps.zdusercontent.com/347982/assets/1633050534-1ca5649b20542a8c9ed713e1b6969dcc/logo-small.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember2263&quot;)/div[@class=&quot;app_view_outer popover-inner&quot;]/div[@class=&quot;iframe_app_view_wrapper&quot;]/header[1]/img[@class=&quot;logo&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember2263']/div[2]/div/header/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://347982.apps.zdusercontent.com/347982/assets/1633050534-1ca5649b20542a8c9ed713e1b6969dcc/logo-small.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/header/img</value>
   </webElementXpaths>
</WebElementEntity>
